<?php

if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('blockify_get_svg_allowed_tags')) {
    function blockify_get_svg_allowed_tags(): array {
        return [
            'svg' => [
                'xmlns' => true,
                'viewbox' => true,
                'viewBox' => true,
                'width' => true,
                'height' => true,
                'preserveAspectRatio' => true,
                'fill' => true,
                'stroke' => true,
                'class' => true,
                'style' => true,
                'aria-hidden' => true,
                'role' => true,
                'xmlns:xlink' => true,
            ],
            'path' => [
                'd' => true,
                'fill' => true,
                'fill-opacity' => true,
                'stroke' => true,
                'stroke-opacity' => true,
                'stroke-width' => true,
                'stroke-linecap' => true,
                'stroke-linejoin' => true,
                'stroke-miterlimit' => true,
                'stroke-dasharray' => true,
                'stroke-dashoffset' => true,
                'fill-rule' => true,
                'clip-rule' => true,
                'clip-path' => true,
                'opacity' => true,
                'transform' => true,
                'style' => true,
            ],
            'circle' => [
                'cx' => true,
                'cy' => true,
                'r' => true,
                'fill' => true,
                'stroke' => true,
                'stroke-width' => true,
                'opacity' => true,
                'transform' => true,
            ],
            'rect' => [
                'x' => true,
                'y' => true,
                'width' => true,
                'height' => true,
                'rx' => true,
                'ry' => true,
                'fill' => true,
                'stroke' => true,
                'stroke-width' => true,
                'opacity' => true,
                'transform' => true,
            ],
            'ellipse' => [
                'cx' => true,
                'cy' => true,
                'rx' => true,
                'ry' => true,
                'fill' => true,
                'stroke' => true,
                'stroke-width' => true,
                'opacity' => true,
                'transform' => true,
            ],
            'g' => [
                'fill' => true,
                'stroke' => true,
                'transform' => true,
                'clip-path' => true,
                'opacity' => true,
                'style' => true,
            ],
            'line' => [
                'x1' => true,
                'y1' => true,
                'x2' => true,
                'y2' => true,
                'stroke' => true,
                'stroke-width' => true,
            ],
            'polygon' => [
                'points' => true,
                'fill' => true,
                'stroke' => true,
                'stroke-width' => true,
                'opacity' => true,
                'transform' => true,
            ],
            'polyline' => [
                'points' => true,
                'fill' => true,
                'stroke' => true,
                'stroke-width' => true,
                'opacity' => true,
                'transform' => true,
            ],
            'defs' => [],
            'clipPath' => [
                'id' => true,
            ],
            'mask' => [
                'id' => true,
                'x' => true,
                'y' => true,
                'width' => true,
                'height' => true,
                'maskUnits' => true,
            ],
            'linearGradient' => [
                'id' => true,
                'x1' => true,
                'y1' => true,
                'x2' => true,
                'y2' => true,
                'gradientUnits' => true,
            ],
            'radialGradient' => [
                'id' => true,
                'cx' => true,
                'cy' => true,
                'r' => true,
                'fx' => true,
                'fy' => true,
                'gradientUnits' => true,
            ],
            'stop' => [
                'offset' => true,
                'stop-color' => true,
                'stop-opacity' => true,
            ],
            'use' => [
                'href' => true,
                'xlink:href' => true,
                'x' => true,
                'y' => true,
            ],
            'symbol' => [
                'id' => true,
                'viewBox' => true,
            ],
            'pattern' => [
                'id' => true,
                'width' => true,
                'height' => true,
                'patternUnits' => true,
            ],
            'style' => [
                'type' => true,
            ],
            'title' => [],
            'desc' => [],
        ];
    }
}
